
name: Deploy App to Azure VM

on:
  workflow_call:
   # secrets:
    #  AZURE_PRIVATE_KEY:
     #   required: true
      #AZURE_USER:
       # required: true
      #AZURE_HOST:
      #  required: true
      #REMOTE_PORT:
      #  required: true
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.AZURE_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Create .env file
        run: |
          echo "FRONTEND_PORT=3000" >> .env
          echo "BACKEND_PORT=8080" >> .env
          echo "MONGO_HOST=mongo" >> .env
          echo "MONGO_PORT=27017" >> .env
          echo "MONGO_DB=testdb" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=admin" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=admin123" >> .env

      - name: Rsync files to Azure VM
        run: |
          rsync -avz -e "ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa" ./ ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }}:/home/${{ secrets.AZURE_USER }}/app/
        shell: bash

      - name: Run docker-compose up remotely
        run: |
          ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} \
            "cd /home/${{ secrets.AZURE_USER }}/app && sudo docker-compose up -d"
        shell: bash

      - name: Collect docker-compose logs remotely
        run: |
          ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} \
            "cd /home/${{ secrets.AZURE_USER }}/app && sudo docker-compose logs" > ./deploy-to-azure-vm.txt
        shell: bash
        continue-on-error: true

      - name: Upload deployment logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-to-azure-vm-logs
          path: ./deploy-to-azure-vm.txt
